### ISSUE TITLE
Roadmap 🚧

### ISSUE THREAD

**Issue by tscpp** [tscpp/conventional-versioning#1]
# High Priority

- [x] ~~Flag (and option) for commiting changes after versioning.~~
  - [x] ~~Option for generating git tags on versioning. Date/sequence/version, optional for prereleases.~~
- [x] ~~Error when no base is set to require running conver init.~~
- [x] Versioning should set the base to the commit before the versioning.
- [x] option to always bump major on breaking changes (even 0.x).
- [x] ~~Feature to release canary pre-releases.~~
- [x] Global changes affect all packages?
- [x] Does merge commits work?
- [x] Option to prevent all major bumps where only promote can bump major.
- [x] If multiple packages have the same path (or workspace path), changes will be ignored.

# Low Priority

- [x] Linked and fixed versions.
- [x] Command for viewing the versioning status.
- [x] Add common cc types to release types.
- [x] Fix support for "!" suffix.
- [x] Add CI checks for build and lint.
- [x] ~~Support for pre-releases before initial release without bumping the stable version (0.1.0).~~
- [x] Promotes are forgotten in pre-release. Set original version or something to bump from.
- [x] Remove `updateWorkspaceDependencies` option.
- [x] Better "single package" support.
- [x] Simplify pre-release config.
- [x] generated schema url is invalid. should start with ./node_modules/
- [x] distinguish 0.x versions from stable versions in conver status :)
- [x] ~~give tag suggestions when doing conver pre enter~~
- [x] Allow comments and trailing comma in config file.
  - [x] Add banner comment to config file exaplaining what this file does.
